import assert from 'node:assert/strict';
import {readFileSync,readdirSync,lstatSync,existsSync} from 'node:fs';
import {createHash} from 'node:crypto';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const expectedAssets=['01-title-logo-v01.png','02-naoto-design-v01.png','03-mio-design-v01.png','04-makoto-design-v01.png','04-makoto-design-v02.png','05-key-visual-v01.png','05-key-visual-v02.png','07-social-preview-v01.png','07-social-preview-v02.png','07-social-preview-v03.png','08-x-header-v01.png','icon.svg','teaser-30s-v02.mp4','world-earth-orbit-v01.png','09-reception-woman-v01.png'];
const expectedRoot=['README.md','.gitignore','.gitattributes','verify.mjs','public-manifest.json','docs'];
assert.deepEqual(readdirSync(root).filter(name=>name!=='.git').sort(),expectedRoot.sort(),'Unexpected repository file');
assert.deepEqual(readdirSync(path.join(root,'docs')).sort(),['.nojekyll','assets','index.html','style.css','world.css','world.js'],'Unexpected public entry');
assert.deepEqual(readdirSync(path.join(root,'docs/assets')).sort(),expectedAssets.sort(),'Unexpected public asset');
const expectedFiles=['docs/.nojekyll','docs/index.html','docs/style.css','docs/world.css','docs/world.js',...expectedAssets.map(name=>`docs/assets/${name}`)].sort();
const manifest=JSON.parse(readFileSync(path.join(root,'public-manifest.json'),'utf8'));
assert.equal(manifest.schema,'public-static-site-v1');
assert.equal(manifest.repository,'kiraboshi-neko/40sai-space-trip-site','Wrong IP owner');
assert(/^[a-zA-Z0-9-]+\/40sai-space-trip-site$/.test(manifest.repository),'Unexpected IP repository');
const [owner,repoName]=manifest.repository.split('/');
assert.equal(manifest.origin,`https://${owner}.github.io/${repoName}`);
assert.deepEqual(manifest.files.map(file=>file.path).sort(),expectedFiles);
for(const name of ['docs','docs/assets']) {
 const stat=lstatSync(path.join(root,name));
 assert(stat.isDirectory()&&!stat.isSymbolicLink(),'Public directory must not be a link');
}
for(const item of manifest.files) {
 const filename=path.join(root,item.path); const stat=lstatSync(filename);
 assert(stat.isFile()&&!stat.isSymbolicLink(),`Not a regular file: ${item.path}`);
 const bytes=readFileSync(filename);
 assert.equal(bytes.length,item.bytes,`Size mismatch: ${item.path}`);
 assert.equal(createHash('sha256').update(bytes).digest('hex'),item.sha256,`Hash mismatch: ${item.path}`);
}
const html=readFileSync(path.join(root,'docs/index.html'),'utf8');
assert(html.includes('<small>著者：綺羅星の猫</small>'),'Public author credit missing');
assert(readFileSync(path.join(root,'README.md'),'utf8').includes('。著者：綺羅星の猫。'),'Repository author credit missing');
assert(!html.includes('{{'),'Unresolved template');
assert(!html.includes('.chatgpt.site'),'Old hosting reference');
assert(html.includes(`rel="canonical" href="${manifest.origin}/"`));
assert(html.includes(`og:image" content="${manifest.origin}/assets/07-social-preview-v03.png"`));
assert(html.includes('高瀬真琴'));
assert.equal(manifest.throughEpisode,30,'Public scope must match the approved publication boundary');
assert(Array.isArray(manifest.episodes),'Published episode metadata missing');
assert.deepEqual(manifest.episodes.map(e=>e.number),Array.from({length:manifest.throughEpisode+1},(_,i)=>i),'Episode gap or future episode');
function groupBounds(number){const start=number<=10?0:Math.floor((number-1)/10)*10+1;return [start,start===0?10:start+9];}
assert.deepEqual(groupBounds(0),[0,10]);
assert.deepEqual(groupBounds(10),[0,10]);
assert.deepEqual(groupBounds(11),[11,20]);
assert.deepEqual(groupBounds(21),[21,30]);
const groups=[...html.matchAll(/<details class="episode-group" id="episodes-(\d+)-(\d+)"(?: open)?><summary>[\s\S]*?<\/summary><div class="episode-list">([\s\S]*?)<\/div><\/details>/g)];
assert.deepEqual(groups.map(g=>[Number(g[1]),Number(g[2])]),[[0,10],[11,20],[21,30]],'Published episode grouping mismatch');
const episodeLinks=[];
for(const group of groups){
 const links=[...group[3].matchAll(/<a href="([^"]+)"[^>]*aria-label="第(\d+)話 ([^"]+)を読む"><span>EPISODE \d+<\/span><strong>([^<]+)<\/strong>/g)];
 assert.equal(links.length,Number(group[2])-Number(group[1])+1,'Missing or duplicate group links');
 for(const link of links){
  const number=Number(link[2]),record=manifest.episodes.find(e=>e.number===number);
  assert(record&&number<=manifest.throughEpisode,'Unpublished episode link');
  assert.deepEqual(groupBounds(number),[Number(group[1]),Number(group[2])],'Episode in the wrong group');
  assert.equal(link[1],record.url);assert.equal(link[3],record.title);assert.equal(link[4],record.title);
  assert.equal(record.url,`https://ncode.syosetu.com/n0686mv/${number+1}/`,'Chapter numbering must include EP0');
  episodeLinks.push(number);
 }
}
assert.deepEqual(episodeLinks,manifest.episodes.map(e=>e.number),'Duplicate or missing published episode');
assert(html.includes('第0話から第30話まで公開中。'));
assert(!html.includes('第0話から第10話まで掲載。'),'Stale publication count');
assert(html.includes('id="episodes-21-30" open'),'Newest published group should be available');
assert(html.includes('class="hero-media"><img class="hero-art"'),'Hero artwork needs its own layout track');
assert(!html.includes('class="hero-shade"'),'Full-cover image overlay is still enabled');
const css=readFileSync(path.join(root,'docs/style.css'),'utf8');
assert(css.includes('.hero .hero-art{position:static;'),'Hero artwork must not cover copy');
assert(css.includes('grid-template-columns:minmax(0,.9fr) minmax(0,1.1fr)'),'Separated desktop layout missing');
assert(css.includes('@media(max-width:1000px)'),'Stacked mobile/tablet layout missing');
assert(html.includes('class="hero-art" src="assets/05-key-visual-v02.png"'),'Updated TOP visual missing');
assert(html.includes('poster="assets/05-key-visual-v02.png"'),'Updated video poster missing');
assert.equal((html.match(/assets\/04-makoto-design-v02\.png/g)||[]).length,3,'Updated Mako portrait and design links missing');
assert.equal((html.match(/assets\/07-social-preview-v03\.png/g)||[]).length,4,'Updated card and sharing images missing');
assert(!/assets\/(?:(?:04-makoto-design|05-key-visual)-v01|07-social-preview-v0[12])\.png/.test(html),'An active Mako image still uses a previous version');
assert.equal((html.match(/<h3>UNKNOWN<\/h3>/g)||[]).length,1);
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(match=>match[1]);
assert.equal(new Set(ids).size,ids.length,'Duplicate anchor');
for(const match of html.matchAll(/(?:src|href|poster)="([^"]+)"/g)) {
 const value=match[1];
 if(value.startsWith('#')) assert(ids.includes(value.slice(1)),`Missing anchor: ${value}`);
 else if(!value.startsWith('https://')) assert(existsSync(path.join(root,'docs',value.split('?')[0])),`Missing resource: ${value}`);
 else assert(value.startsWith(`${manifest.origin}/`)||value==='https://ncode.syosetu.com/n0686mv/'||manifest.episodes.some(e=>e.url===value),`Unexpected external URL: ${value}`);
}
assert(html.includes('controls playsinline')&&html.includes('assets/teaser-30s-v02.mp4'),'Instrumental video missing');
assert(!/<track\b/.test(html),'Browser captions would duplicate burned-in subtitles');
assert(html.includes('class="pv-transcript"'),'Accessible transcript missing');
assert.equal(manifest.world.throughEpisode,30,'World guide must not exceed approved episode scope');
assert.deepEqual(manifest.world.locations,['earth','station']);
assert.deepEqual(manifest.world.spots,['dining','work','cabin','window']);
assert.equal(manifest.world.illustrationOnly,true);
assert(html.includes('world.css?v=20261003-receipt'));
assert(html.includes('src="world.js?v=20261003-receipt" defer'));
assert(html.includes('id="world-log"')||html.includes('class="world-log"'),'No-JS guide missing');
assert(html.includes('施設の公式構造図や物理シミュレーションではありません'));
assert(html.includes('id="world-fix" aria-pressed="true"'));
assert(!html.includes('公開済みの世界：地球。その他のエリアは非公開'),'Stale world scope');
const worldScript=readFileSync(path.join(root,'docs/world.js'),'utf8');
const worldStyle=readFileSync(path.join(root,'docs/world.css'),'utf8');
assert(!/\b(?:fetch|XMLHttpRequest|WebSocket|eval)\s*\(|localStorage|sessionStorage|innerHTML|document\.cookie/.test(worldScript),'World guide must be local, non-tracking and text-only');
assert(!/HIDDEN_CANON|UNPUBLISHED|engineOnly|secretFacts|revealAtEpisode/.test(worldScript),'Non-public world metadata');
assert(worldStyle.includes('@media(prefers-reduced-motion:reduce)'));
assert(worldStyle.includes('[data-motion="paused"]'));
assert(worldStyle.includes('max-width:760px'));
assert(html.includes('class="world-space-art" src="assets/world-earth-orbit-v01.png"'));
assert(!/class="(?:world-stars|world-earth|world-continents)"/.test(html),'Old synthetic globe layer remains');
assert(worldStyle.includes('world-orbit-drift')&&worldStyle.includes('object-fit:cover'),'Earth background presentation missing');
const orbit=readFileSync(path.join(root,'docs/assets/world-earth-orbit-v01.png'));
assert.equal(orbit.subarray(0,8).toString('hex'),'89504e470d0a1a0a','Earth background must be PNG');
assert(orbit.readUInt32BE(16)>=1024&&orbit.readUInt32BE(20)>=1024,'Background resolution too small');
const ignored=readFileSync(path.join(root,'.gitignore'),'utf8');
assert(ignored.split(/\r?\n/).includes('!/docs/world.css')&&ignored.split(/\r?\n/).includes('!/docs/world.js'),'WORLD assets must be explicitly allowed for Git');
assert(ignored.split(/\r?\n/).includes('!/docs/assets/world-earth-orbit-v01.png'),'Earth background must be explicitly allowed for Git');
assert.equal(manifest.characters.throughEpisode,30);
assert.deepEqual(manifest.characters.revealed.map(c=>c.id),['reception-woman','station-desk']);
assert.deepEqual(manifest.characters.revealed.map(c=>c.firstEpisode),[21,19]);
assert.deepEqual(manifest.characters.revealed.map(c=>c.label),['受渡室の女性','笹倉さん']);
assert.equal(manifest.characters.revealed[0].nameDisclosed,false);
assert.equal(manifest.characters.illustrationOnly,true);
const revealed=html.match(/<details class="character-reveal" id="character-21-30">([\s\S]*?)<\/details>/);
assert(revealed,'New character introductions must be closed by default');
assert(revealed[1].includes('第21〜30話を読んだ方向け'));
for(const character of manifest.characters.revealed){
 assert(revealed[1].includes('id="'+character.id+'"'),'Character outside reader gate');
 assert(revealed[1].includes('初登場：第'+character.firstEpisode+'話を読む'));
}
assert.equal((revealed[1].match(/<dd>未判明<\/dd>/g)||[]).length,2);
assert(html.includes('本文に未記載の造形は設定の確定を意味しません'));
assert(html.includes('src="assets/09-reception-woman-v01.png"'));
const portrait=readFileSync(path.join(root,'docs/assets/09-reception-woman-v01.png'));
assert.equal(portrait.subarray(0,8).toString('hex'),'89504e470d0a1a0a');
assert(portrait.readUInt32BE(16)>=1024&&portrait.readUInt32BE(20)>portrait.readUInt32BE(16));
assert(ignored.split(/\r?\n/).includes('!/docs/assets/09-reception-woman-v01.png'));
assert.equal(manifest.world.mealTerminal.illustrationOnly,true);
assert.deepEqual(manifest.world.mealTerminal.ticketNumbers,['01','02','03']);
assert.equal(manifest.world.mealTerminal.remoteRequests,false);
assert.equal(manifest.world.mealTerminal.audio,false);
assert(html.includes('id="meal-terminal" data-receipt="waiting" aria-labelledby="meal-title" hidden'));
assert.deepEqual([...html.matchAll(/data-meal-ticket="([^"]+)"/g)].map(m=>m[1]),['01','02','03']);
assert(html.includes('id="meal-status" role="status" aria-live="polite"'));
assert(html.includes('番号と動きは紹介用イメージです'));
assert(worldStyle.includes('.world-atlas[data-motion="paused"] .meal-bag{animation:none}'));
assert(!/<audio\b|\bautoplay\b|<iframe\b/.test(html),'No automatic sound or external frames');
const publicText=[html,css,worldStyle,worldScript,readFileSync(path.join(root,'README.md'),'utf8')].join('\n');
assert(!/file:\/\/|[A-Z]:[\\/]|Users[\\/]|generated_images|\.prompt\.|OPENAI_API_KEY|AKIA[0-9A-Z]{16}/.test(publicText),'Private path, prompt or credential marker');
assert(!/\b(?:fetch|XMLHttpRequest|WebSocket|eval|Audio)\s*\(|localStorage|sessionStorage|innerHTML|document\.cookie|setInterval/.test(worldScript),'No remote requests, tracking or sound');
console.log(JSON.stringify({verified:true,publicFiles:expectedFiles.length,unknownSlots:1,throughEpisode:manifest.throughEpisode,episodeLinks:episodeLinks.length,groups:groups.length,heroSeparated:true,worldLocations:manifest.world.locations,worldSpots:manifest.world.spots,worldIllustrationOnly:true,readerGatedCharacters:2,mealTerminal:true,exactAllowlist:true,sha256:true}));
